import type { Metadata } from "next";
import "./globals.css";
import "../styles/nav.scss";
import "../styles/footer.scss";
import "../styles/homebanner.scss";
import "../styles/card.scss";
import "../styles/productcard.scss";






export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

        {children}

      </body>
    </html>
  );
}
